--Estas con las consultas SQL para LAFT
-- QUERYS LAFT--
--NUEVO PAQUQETES
--USUARIOS
SELECT * FROM TBL_LAFT_USUARIO for update

--PERFILES
SELECT * FROM TBL_LAFT_PROFILES;

--CARGO
SELECT * FROM TBL_LAFT_CARGO;

--ALERTA POR PERFIL
SELECT * FROM TBL_LAFT_ALERTA_PERFIL;

--PERFILES POR SEÑAL
SELECT * FROM TBL_LAFT_PROFILES_X_GRUPO_SENAL;

--PERFIL POR MENU
SELECT * FROM TBL_LAFT_PROFILES_RESOURCE;

--ALERTAS
SELECT * FROM TBL_LAFT_ALERTA;

--PREGUNTA X PREGUNTA
SELECT * FROM TBL_LAFT_ALERTA_PREGUNTA;

--COMPLEMENTOS
SELECT * FROM TBL_LAFT_ALERTA_COMPLEMENTO

--CORREOS CONFIGURADOS
SELECT * FROM TBL_LAFT_CONFIGURACION_CORREO;

--ACCION DE CORREOS
SELECT * FROM TBL_LAFT_ACCIONES_CORREO

--REGIMENES
SELECT * FROM TBL_LAFT_REGIMEN;

--TIPO DE LISTAS
SELECT * FROM TBL_LAFT_TIPO_LISTA;

--PROVEEDORES
SELECT * FROM TBL_LAFT_PROVEEDOR;

--NOMBRE DE LOS MENUS
SELECT * FROM TBL_LAFT_RESOURCE for update;

--GRUPOS
SELECT * FROM TBL_LAFT_GRUPO_SENALES;

--SUBGRUPO X GRUPO
SELECT * FROM TBL_LAFT_SUB_GRUPO_SENALES

--ADJUNTOS
SELECT * FROM TBL_LAFT_ALERTA_CAB_USU_ADJ;

--COMENTARIOS
SELECT * FROM TBL_LAFT_ALERTA_CAB_USU_COMENT;

--ESTADOS DE GESTOR CLIENTE
SELECT * FROM TBL_LAFT_TRATAM_CLIENTE_HIS ;

--RESULTADO DE COINCIDENCIAS
SELECT * FROM TBL_LAFT_ALERTA_RESULTADOS WHERE NIDSUBGRUPOSEN = 2
SELECT * FROM TBL_LAFT_ALERTA_RESULTADOS WHERE NPERIODO_PROCESO  = '20221231' AND NIDPROVEEDOR = 1
SELECT * FROM TBL_LAFT_ALERTA_RESULTADOS WHERE NPORC_APROXIMA_BUSQ > 90  AND NIDPROVEEDOR = 4
SELECT * FROM TBL_LAFT_ALERTA_RESULTADOS WHERE SNOM_COMPLETO LIKE '%OLLANTA HUMALA TASSO%'
AND NPERIODO_PROCESO  = '20230331'
AND DNULLDATE IS NULL


SELECT * FROM TBL_LAFT_ALERTA_RESULTADOS WHERE SNUM_DOCUMENTO = '08774976'

SELECT * FROM TBL_LAFT_ALERTA_RESULTADOS WHERE NIDALERTA = '39'
SELECT * FROM TBL_LAFT_ALERTA_RESULTADOS WHERE SNOM_COMPLETO_BUSQ = 'TIRAPO SANCHEZ ALEJANDRO GENARO' FOR UPDATE
SELECT * FROM TBL_LAFT_CLIENTES_VIGENTES WHERE NPERIODO_PROCESO  = '20221231'
  AND DCOMPDATE BETWEEN TO_DATE('12/01/2023' || ' 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
  AND TO_DATE('13/01/2023' || ' 00:00:00', 'DD/MM/YYYY HH24:MI:SS')

SELECT * FROM laft.TBL_LAFT_ALERTA_OTROS_CLIENTES
WHERE SNOM_COMPLETO = 'QUISPE QUISPE JOSE'

 WHERE SNUM_DOCUMENTO = '799923';
SELECT * FROM TBL_LAFT_ALERTA_OTROS_CLIENTES WHERE SNOM_COMPLETO = 'ABUGATTAS SIMONS JIM ALAN JOHN'
SELECT * FROM TBL_LAFT_ALERTA_OTROS_CLIENTES WHERE NPERIODO_PROCESO = '20230331' AND NIDGRUPOSENAL =2

SELECT * FROM TBL_LAFT_ALERTA_OTROS_CLIENTES WHERE NPERIODO_PROCESO = '20221231' AND NIDGRUPOSENAL = 4 AND NIDSUBGRUPOSEN = 3 AND NIDALERTA = 39

SELECT * FROM laft.TBL_LAFT_ALERTA_RESULTADOS WHERE SNUM_DOCUMENTO_BUSQ  = '07915664' AND NPERIODO_PROCESO = '20230331'
SELECT * FROM TBL_LAFT_TMP_CLIENTES_FAM_PEP WHERE SNUM_DOCUMENTO = '25612447';
SELECT * FROM TBL_LAFT_ALERTA_TRATAM_CLIENTE WHERE SNUM_DOCUMENTO = '07214339';
SELECT * FROM TBL_LAFT_CLIENTES_VIGENTES WHERE SPRODUCTO = 'RT'
SELECT * FROM TBL_LAFT_CLIENTES_VIGENTES WHERE NPERIODO_PROCESO = '20230331'

SELECT * FROM laft.TBL_LAFT_ALERTA_LISTA_EXTERNO WHERE SNOM_COMPLETO = 'TENAZOA ARMAS EDITH'


SELECT * FROM TBL_LAFT_ALERTA_OTROS_CLIENTES_MANUAL WHERE SNUM_DOCUMENTO= '34536'

--REGISTRO NEGATIVO
SELECT * FROM laft.TBL_LAFT_CLIENTE_REG_NEGATIVO WHERE SNUMIDENTIDAD = '10866456'

SELECT * FROM TBL_LAFT_ALR_PROC_ADJUN_INFORM
SELECT * FROM TBL_LAFT_ALERTA_LISTA_EXTERNO
SELECT * FROM TBL_LAFT_USUARIO_HISTORIAL

SELECT * FROM TBL_LAFT_ALERTA_OTROS_CLIENTES WHERE NIDGRUPOSENAL=3 AND NIDSUBGRUPOSEN = 2

 --TABLA DE LAS CARGAS DE INFORMACION
  --REGISTRO NEGATIVO
  SELECT * FROM TBL_LAFT_CLIENTE_REG_NEGATIVO WHERE SNOM_COMPLETO LIKE '%ALEJANDRO TOLEDO%'

  --REGISTRO ACTIVIDAD ECONOMICA
  SELECT * FROM TBL_LAFT_SECTOR_KRI FOR UPDATE
  SELECT * FROM TBL_LAFT_ACTIVIDAD_ECONOMICA FOR UPDATE
  SELECT * FROM TBL_LAFT_ACTIVIDAD_ECONOMICA_EQFX

  --REGISTRO ZONA GEOGRAFICA
  SELECT * FROM TBL_LAFT_KRI_ZONA_GEOGRAFICA WHERE NUM_IDENBEN = '16498677'

  --REGISTRO ANEXO ES10
  SELECT * FROM TBL_LAFT_REGIMEN_RAMO
  SELECT * FROM TBL_LAFT_PLANTILLA_ES10

  --TABLAS WORLDCHECK
  SELECT * FROM TBL_LAFT_WC1_COINCIDENCIA;
  SELECT * FROM TBL_LAFT_WC1_COINCIDENCIA_SOURCE;
  SELECT * FROM TBL_LAFT_WC1_COINCIDENCIA_CATEGORIES;
  SELECT * FROM TBL_LAFT_WC1_COINCIDENCIA_EVENTS;
  SELECT * FROM TBL_LAFT_WC1_COINCIDENCIA_COUNTRYLINKS;
  SELECT * FROM TBL_LAFT_WC1_COINCIDENCIA_IDENTITYDOCUMENTS;
  SELECT * FROM TBL_LAFT_WC1_PROFILE;
  SELECT * FROM TBL_LAFT_WC1_DETAIL
  SELECT * FROM TBL_LAFT_WC1_DETAIL_SOURCE

  SELECT * FROM TBL_LAFT_ALERTA_INFORME_N1 for update

LAFT.TBL_LAFT_INFORME_N1_FORMATO
PKG_LAFT_REPORTE_N1
SP_GET_ZGEOGRAFIC_PRODUCT_CLIENTES

  --TABLAS DEL INFORME N1
  SELECT * FROM TBL_LAFT_ALERTA_INFORME_N1
  SELECT * FROM TBL_LAFT_GRUPO_PRODUCTO_N1
  SELECT * FROM TBL_LAFT_PRODUCTO_N1
  SELECT * FROM TBL_LAFT_

LAFT.TBL_LAFT_INFORME_N1_FORMATO
PKG_LAFT_REPORTE_N1
SP_GET_ZGEOGRAFIC_PRODUCT_CLIENTES


SELECT * FROM INSUDB.TABLE66;

--LISTAS GAFI
SELECT * FROM TBL_LAFT_LISTA_GAFI_ACT FOR UPDATE;
SELECT * FROM LAFT.TBL_LAFT_LISTA_GAFI
SELECT * FROM TBL_LAFT_CLIENTES_VIGENTES where SNUM_DOCUMENTO = '00369233';
SELECT DISTINCT * FROM LAFT.TBL_LAFT_ALERTA_RESULTADOS_GAFI where NIDGRUPOSENAL = 1 AND NIDSUBGRUPOSEN = 0


SELECT * FROM CLIENT_SUNAT


SELECT * FROM TABLE66;



SELECT distinct stipo_lista_referencia FROM LAFT.TBL_LAFT_ALERTA_LISTA_EXTERNO
WHERE NPERIODO_PROCESO=20230331
AND NIDPROVEEDOR=3;


SELECT * FROM TBL_LAFT_USUARIO_HISTORIAL ORDER BY DFECHA_REGISTRO DESC FOR UPDATE;
SELECT * FROM TBL_LAFT_USUARIO ORDER BY FECHA_REG DESC FOR UPDATE;

SELECT * FROM TBL_LAFT_USUARIO_HISTORIAL WHERE USUARIO = 'AALVARADO';
SELECT * FROM TBL_LAFT_USUARIO WHERE USUARIO = 'AALVARADO';


SELECT * FROM TBL_LAFT_ALERTA_LISTA_EXTERNO WHERE SNOM_COMPLETO LIKE '%OLLANTA HUMALA TASSO%' and NPERIODO_PROCESO=20230331
SELECT * FROM LAFT.TBL_LAFT_ALERTA_LISTA_EXTERNO WHERE  SNUM_DOCUMENTO = '799923'
