pruebas SQL
SELECT * FROM LIFE_COVER where NBRANCH=73


--mejoras en el codigo

--se realizan cambios en el uso de git

-- nuevva mejora de la mejora


---nueva pruebita

--se egrego el nuevo query

SELECT * FROM LIFE_COVER WHERE NBRANCH = 73 AND NPRODUCT = 1 AND NMODULEC = 22 AND NCOVER = 6;

--prueba final para agregar un query

--------------------------- POLICY ----------------------------------------
SELECT SCERTYPE,NBRANCH,NPOLICY,SCLIENT,NPRODUCT,DCHANGDAT,DCOMPDATE,DDATE_ORIGI,DSTARTDATE,DEXPIRDAT,DISSUEDAT,DNULLDATE,DNEXTRECEIP,NCAPITAL,NPARTICIP,NPREMIUM,NPAYFREQ,NINTERMED,NLAST_CERTI,SCOLINVOT,SCOLTIMRE,SCOMMITYP,SPOLITYPE,SSTATUS_POL
 FROM POLICY SSTATUS_POL
WHERE NPOLICY= 2000002554;

