pruebas SQL
SELECT * FROM LIFE_COVER where NBRANCH=73

select * from tbl_pd_cotizacion_cab where nid_cotizacion=41854

--- nuevo cambio
--mejoras en el codigo

--se realizan cambios en el uso de git

-- nuevva mejora de la mejora


---nueva pruebita

--se egrego el nuevo query

SELECT * FROM LIFE_COVER WHERE NBRANCH = 73 AND NPRODUCT = 1 AND NMODULEC = 22 AND NCOVER = 6;

--prueba final para agregar un query

--------------------------- POLICY ----------------------------------------
SELECT SCERTYPE,NBRANCH,NPOLICY,SCLIENT,NPRODUCT,DCHANGDAT,DCOMPDATE,DDATE_ORIGI,DSTARTDATE,DEXPIRDAT,DISSUEDAT,DNULLDATE,DNEXTRECEIP,NCAPITAL,NPARTICIP,NPREMIUM,NPAYFREQ,NINTERMED,NLAST_CERTI,SCOLINVOT,SCOLTIMRE,SCOMMITYP,SPOLITYPE,SSTATUS_POL
 FROM POLICY SSTATUS_POL
WHERE NPOLICY= 2000002554;



---- Consulta para  obtener la cotización , categoria , tasa, prima neta , producto , ramo , poliza , monto de planilla , plan , frecuencia de pago  y tipo de renovacion


SELECT T1.NID_COTIZACION, (SELECT SDESCRIPT FROM TBL_PD_TYPE_EMPLOYEE WHERE NTYPE_EMPLOYEE = NMODULEC) AS CATEGORIA,
           NTASA_CALCULADA, NPREMIUM_MENSUAL,NPRODUCT,NBRANCH,npolicy,
          CASE WHEN PV_REA_MOV_COTIZA_HIS(T1.NID_COTIZACION, 0, 'NPAYFREQ') = 5 THEN 1 *  NPREMIUM_MEN_AUT
                   WHEN PV_REA_MOV_COTIZA_HIS(T1.NID_COTIZACION, 0, 'NPAYFREQ') = 4 THEN 2 *  NPREMIUM_MEN_AUT
                   WHEN  PV_REA_MOV_COTIZA_HIS(T1.NID_COTIZACION, 0, 'NPAYFREQ') = 3 THEN 3 *  NPREMIUM_MEN_AUT
                   WHEN PV_REA_MOV_COTIZA_HIS(T1.NID_COTIZACION, 0, 'NPAYFREQ')= 2 THEN 6 *  NPREMIUM_MEN_AUT
                   WHEN PV_REA_MOV_COTIZA_HIS(T1.NID_COTIZACION, 0, 'NPAYFREQ') = 1 THEN 12 *  NPREMIUM_MEN_AUT
          END AS PRIMA_TOTAL, NMONTO_PLANILLA,
           (SELECT UPPER(SDESCRIPT) FROM TBL_PD_PLAN_VL WHERE NCODPLAN = (SELECT NIDPLAN FROM TBL_PD_COTIZACION_CAB WHERE NID_COTIZACION = T1.NID_COTIZACION) AND ROWNUM = 1) AS PLAN,
          (SELECT SDESCRIPT FROM TABLE36 WHERE NPAYFREQ =PV_REA_MOV_COTIZA_HIS(T1.NID_COTIZACION, 0, 'NPAYFREQ')) AS FRECUENCIA_PAGO,
          (SELECT SDESCRIPT FROM TABLE35 WHERE NTIP_RENOV = (SELECT NTIP_RENOV FROM TBL_PD_COTIZACION_CAB WHERE NID_COTIZACION = T1.NID_COTIZACION )) AS TIPO_RENOVACION
FROM TBL_PD_COTIZACION_DET T1
WHERE NID_COTIZACION IN
(
40222
)
AND DNULLDATE IS NULL
ORDER BY NID_COTIZACION, T1.NMODULEC

----AGREGAR UN NUEVO CODIGO






