/*SCRIPT ANULACION DE DEUDA*/
DECLARE

/*Variables de configuracion*/ -- INPUT
L_SCLINUMDOCU                 CLIDOCUMENTS.SCLINUMDOCU%TYPE := '20510713363';
L_NBRANCH                     POLICY.NBRANCH%TYPE := 77;

/*Variables internas*/ -- NO TOCAR
L_SCERTYPE                    POLICY.SCERTYPE%TYPE;
L_NPRODUCT                    POLICY.NPRODUCT%TYPE;
L_NPOLICY                     POLICY.NPOLICY%TYPE;
L_SCLIENT                     CLIENT.SCLIENT%TYPE;
L_NVAL                        NUMBER(1);
L_NERR                        NUMBER(1) := 0;

CURSOR C_CLIENT IS
SELECT C.SCLIENAME AS CONTRATANTE
     , TRIM(CI.SCLINUMDOCU) AS DOCUMENTO
     , TO_CHAR(SYSDATE,'DD/MM/YYYY') AS FECHA_ACTUAL
     , C.SCLIENT AS SCLIENT
  FROM CLIENT C
     , CLIDOCUMENTS CI
 WHERE UPPER(CI.SCLINUMDOCU) = UPPER(L_SCLINUMDOCU)
   AND UPPER(C.SCLIENT) = CI.SCLIENT;

CURSOR C_POLIZAS IS
SELECT R.SCERTYPE
     , R.NPRODUCT
     , R.NPOLICY
  FROM ROLES R
 WHERE R.NBRANCH = L_NBRANCH
   AND R.NCERTIF = 0
   AND R.NROLE = 1
   AND R.SCLIENT = L_SCLIENT
   AND R.DNULLDATE IS NULL
   AND EXISTS ( SELECT 1
                  FROM PREMIUM P
                     , BILLS B
                 WHERE P.SCERTYPE = R.SCERTYPE
                   AND P.NBRANCH = R.NBRANCH
                   AND P.NPRODUCT = R.NPRODUCT
                   AND P.NPOLICY = R.NPOLICY
                   AND B.NINSUR_AREA = P.NINSUR_AREA
                   AND B.SBILLTYPE = P.SBILLTYPE
                   AND B.NBILLNUM = P.NBILLNUM
                   AND B.NBILLSTAT = 3 );

CURSOR C_RECIBOS IS
SELECT P.NPOLICY AS POLIZA
     --, TO_CHAR(B.DBILLDATE,'DD/MM/YYYY') AS FECHA_EMISION
     , B.NINSUR_AREA
     , B.SBILLTYPE
     , B.NBILLNUM
     , P.NRECEIPT
     , B.NBILLSTAT
     , ( SELECT TRIM(T5564.SDESCRIPT)
           FROM TABLE5564 T5564
          WHERE T5564.NBILLSTAT = B.NBILLSTAT
            AND T5564.SSTATREGT = '1' ) AS SDESCRIPT
  FROM PREMIUM P
     , BILLS B
 WHERE P.SCERTYPE = L_SCERTYPE
   AND P.NBRANCH = L_NBRANCH
   AND P.NPRODUCT = L_NPRODUCT
   AND P.NPOLICY = L_NPOLICY
   AND P.DNULLDATE IS NULL
   AND P.NINSUR_AREA > 0
   AND ( TRIM(P.SBILLTYPE) IS NOT NULL OR TRIM(P.SBILLTYPE) != '' )
   AND P.NBILLNUM > 0
   AND B.NINSUR_AREA = P.NINSUR_AREA
   AND B.SBILLTYPE = P.SBILLTYPE
   AND B.NBILLNUM = P.NBILLNUM
   AND B.SBILLTYPE IN ('5', '6')
   AND B.NBILLNUM > 0
   AND B.NBILLSTAT = 3
   AND PKG_PV_VAL_BLOCK_CLIENT.REA_SUM_NC( P_NRECEIPT => P.NRECEIPT ) = 1
 ORDER BY P.DISSUEDAT;

BEGIN
  FOR X IN C_CLIENT LOOP
EXIT WHEN C_CLIENT%NOTFOUND;
    IF L_NERR = 0 THEN
      L_SCLIENT := X.SCLIENT;

      DBMS_OUTPUT.put_line( '--SCLIENT: ' || X.SCLIENT );

      FOR Y IN C_POLIZAS LOOP
      EXIT WHEN C_POLIZAS%NOTFOUND;
        L_SCERTYPE := Y.SCERTYPE;
        L_NPRODUCT := Y.NPRODUCT;
        L_NPOLICY := Y.NPOLICY;

        DBMS_OUTPUT.put_line( '  POLIZA: ' || Y.NPOLICY );

        FOR Z IN C_RECIBOS LOOP
        EXIT WHEN C_RECIBOS%NOTFOUND;
          UPDATE BILLS B
             SET B.NBILLSTAT = 4
           WHERE B.NINSUR_AREA = Z.NINSUR_AREA
             AND B.SBILLTYPE = Z.SBILLTYPE
             AND B.NBILLNUM = Z.NBILLNUM;
          L_NVAL := SQL%ROWCOUNT;

          IF L_NVAL = 1 THEN
            DBMS_OUTPUT.put_line( '    RECIBO: ' || Z.NRECEIPT || ' | COMPROBANTE: ' || Z.NINSUR_AREA || ' -- ' || Z.SBILLTYPE || '-' || Z.NBILLNUM || ' | ESTADO: ' || Z.SDESCRIPT || ' -> Cobrado/Devuelto' );
          ELSIF L_NVAL = 0 THEN
            DBMS_OUTPUT.put_line( '    RECIBO: ' || Z.NRECEIPT || ' | COMPROBANTE: ' || Z.NINSUR_AREA || ' -- ' || Z.SBILLTYPE || '-' || Z.NBILLNUM || ' | ESTADO: ' || Z.SDESCRIPT || ' X Sin cambios' );
          ELSE
            DBMS_OUTPUT.put_line( '    RECIBO: ' || Z.NRECEIPT || ' | COMPROBANTE: ' || Z.NINSUR_AREA || ' -- ' || Z.SBILLTYPE || '-' || Z.NBILLNUM || ' | ESTADO: ' || ' -> Error: Se han actualizado mas de 2 recibos.' );
            L_NERR := 1;
            ROLLBACK;
            EXIT ;
          END IF;
        COMMIT;
        END LOOP;
      END LOOP;
    ELSE
      EXIT;
      END IF;
      COMMIT;
  END LOOP;
END;

